name: Check Imports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Check Imports
      run: ./vendor/bin/check_imports
